services:

  backend:
    build: ./app/backend

    container_name: guerreiras-backend

    restart: always

    ports:
      - "3000:3000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./app/front-end-vite

    container_name: guerreiras-frontend

    restart: always

    ports:
      - "5173:5173"

    depends_on:
      - backend